version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    commands:
      - yarn
  build:
    commands:
      - yarn build
      - yarn test
post_build:
    commands:
      - echo cp to s3...
      - aws s3 cp build/* s3://testing-arcada-devops --acl public-read --recursive
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    name: build-$(date +%Y-%m-%d)
    base-directory: 'build'