version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    commands:
      - yarn
  build:
    commands:
      - yarn build & aws s3 sync ./build s3://testing-arcada-devops
      - yarn test
post_build:
    commands:
      - echo cp to s3...
      # - ./s3Copy.sh ./build s3://testing-arcada-devops
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    name: build-$(date +%Y-%m-%d)
    base-directory: 'build'